### ISSUE TITLE
Adding a code example to the Registrable section in First Steps doc

### ISSUE THREAD

**Issue by jagnusson** [allenai/tango#302]
**Is your feature request related to a problem? Please describe.**
When initially going through the [First Steps](https://ai2-tango.readthedocs.io/en/latest/first_steps.html) guide, I found the [Registrable section](https://ai2-tango.readthedocs.io/en/latest/first_steps.html#registrable) to be less clear than the rest of the document (though all of it is quite good!) I did find the in-text example of `TorchTrainerStep` taking registrable classes such as `Model` and `Optimizer` as inputs good for motivating the need to swap out subclasses frictionlessly. But without a code example to accompany it, it was still unclear to me what Registrables were doing to address this.

After using the library a bit, it was clear to me that without registrables researchers would have to change lots of type hints in code rather than just changing the config.jsonnet file to make experimental variations. But other than for the step objects (which are a bit more mysterious than just user defined objects), this dynamic does not appear in the code examples. Thus when I first read this, I was actually unaware that a config.jsonnet could have a field of a Step populated by another dictionary with its own "type" field (as in the example proposed below).

**Describe the solution you'd like**
I propose adding a code example to this section of the guide. It could be something along the lines of the following:

```json
{
  "steps": {
    "train": {
      "type": "train",
      "model": {
        "type": "architecture1", # or "architecture2",
        ...
      }
    }
  }
}
```

```python
from tango import Step
from tango.common import FromParams, Registerable

class Model(Registerable):
    ...

@Model.register("architecture1")
class Architecture1(Model):
    ...

@Model.register("architecture2")
class Architecture2(Model):
    ...

@Step.register("train")
class TrainerStep(Step):
    def run(self, model: Model) -> Model:
        ...
```

**Describe alternatives you've considered**
I'd also considered making an abstract foo, bar, baz style example. This has the advantage that it is possible to include complete code without ellipses. However I do really like the existing motivation provided by using the case of a trainer and its inputs.

**Comment by epwalsh** [comment]
This would be great to have. Feel free to make a PR 🤘
