### ISSUE TITLE
A fresh install of Tango cannot find jsonpickle

### ISSUE THREAD

**Issue by schmmd** [allenai/tango#352]
### 🐛 Describe the bug

```
pip install 'ai2-tango[all]'
```

```
michaels@MacBook-Pro-3 ~/h/a/tango (main)> python
Python 3.9.12 (main, Jun  1 2022, 06:36:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonpickle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jsonpickle'
>>> 
```

### Versions

absl-py==1.2.0
ai2-tango==0.11.0
aiohttp==3.8.1
aiosignal==1.2.0
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.1.0
base58==2.1.1
beaker-py==1.6.9
boto3==1.24.48
botocore==1.27.48
cached-path==1.1.5
cachetools==5.2.0
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_83242e7e-f82d-4a71-8ef2-9d71d212d249gu_wxmeq/croots/recipe/certifi_1655968827803/work/certifi
charset-normalizer==2.1.0
chex==0.1.4
click==8.1.3
click-help-colors==0.9.1
commonmark==0.9.1
cycler==0.11.0
datasets==2.4.0
dill==0.3.5.1
dm-tree==0.1.7
docker==5.0.3
docker-pycreds==0.4.0
etils==0.7.1
fairscale==0.4.6
filelock==3.7.1
flatbuffers==1.12
flax==0.5.0
fonttools==4.34.4
frozenlist==1.3.1
fsspec==2022.7.1
gast==0.4.0
gitdb==4.0.9
GitPython==3.1.27
glob2==0.7
google-api-core==2.8.2
google-auth==2.10.0
google-auth-oauthlib==0.4.6
google-cloud-core==2.3.2
google-cloud-storage==2.5.0
google-crc32c==1.3.0
google-pasta==0.2.0
google-resumable-media==2.3.3
googleapis-common-protos==1.56.4
grpcio==1.47.0
h5py==3.7.0
huggingface-hub==0.8.1
idna==3.3
importlib-metadata==4.12.0
importlib-resources==5.9.0
jax==0.3.15
jaxlib==0.3.15
jmespath==1.0.1
joblib==1.1.0
jsonnet==0.18.0
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==14.0.6
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
more-itertools==8.14.0
msgpack==1.0.4
multidict==6.0.2
multiprocess==0.70.13
numpy==1.23.1
oauthlib==3.2.0
opt-einsum==3.3.0
optax==0.1.3
packaging==21.3
pandas==1.4.3
pathtools==0.1.2
petname==2.6
Pillow==9.2.0
promise==2.3
protobuf==3.19.4
psutil==5.9.1
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.9.1
pyDeprecate==0.3.2
Pygments==2.12.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytorch-lightning==1.6.5
pytz==2022.1
PyYAML==6.0
regex==2022.7.25
requests==2.28.1
requests-oauthlib==1.3.1
responses==0.18.0
rich==12.5.1
rsa==4.9
s3transfer==0.6.0
sacremoses==0.0.53
scipy==1.9.0
sentencepiece==0.1.97
sentry-sdk==1.9.3
setproctitle==1.3.1
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
sqlitedict==2.0.0
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-cpu==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
tokenizers==0.12.1
toolz==0.12.0
torch==1.12.1
torchmetrics==0.9.3
tqdm==4.64.0
transformers==4.21.1
typing_extensions==4.3.0
urllib3==1.26.11
wandb==0.12.21
websocket-client==1.3.3
Werkzeug==2.2.2
wrapt==1.14.1
xxhash==3.0.0
yarl==1.8.1
zipp==3.8.1

**Comment by epwalsh** [comment]
The `jsonpickle` dependency was not part of the last release. Tango has only needed `jsonpickle` since the `BeakerExecutor` PR merged, which has not made it into a release yet.
