### ISSUE TITLE
Need to delete workspace when changing requirements

### ISSUE THREAD

**Issue by schmmd** [allenai/tango#355]
### 🐛 Describe the bug

When using the Beaker executor, I need to use a fresh workspace whenever I change requirements or it will used the requirements I had specified in the previous run.  This might be by design...

### Versions

Latest

**Comment by epwalsh** [comment]
What do you mean by "fresh workspace"? Are you referring to a Beaker workspace or a Tango workspace? As long as you commit your changes to your requirements spec file (`requirements.txt` / `environment.yml`) the Beaker executor should use what's up-to-date.

**Comment by schmmd** [comment]
I mean my Tango workspace.  I can verify this sometime to make sure I reported the problem accuretly.
