### ISSUE TITLE
Can steps be defined in different `.py` files in a directory?

### ISSUE THREAD

**Issue by BigRedT** [allenai/tango#365]
All the examples in this Tango repo seem to have all steps defined in a single `.py` file. 

Is it possible to instead have these steps defined in different files within a python package?

For example, how do we use Tango if we have the following directory structure where the Tango steps are defined in the `*_step.py` files:

```
project_dir/
|--preprocess/
|--|--preprocess_steps.py
|--train/
|--|--train_steps.py
|--evaluation/
|--|--eval_steps.py
```

**Comment by epwalsh** [comment]
Hey Tanmay, that is totally fine. They don't even need to part of the same parent directory / module. The `include_package` / `--include-package` setting / command-line argument take multiple values, and act recursively on modules. So in your example, you could either do this:

```bash
tango run config.jsonnet \
  --include-package preprocess/preprocess_steps.py \
  --include-package train/train_steps.py \
  --include-package evaluation/eval_steps.py
```

Or - if your `project_dir/`, `preprocess/`, `train/`, and `evaluation/` directories are actual Python modules (have an `__init__.py` file in each) - you could just do this:

```bash
tango run config.jsonnet --include-package project_dir
```

In the latter, Tango will recursively import all modules that are submodules of the `project_dir` module.

Equivalently you could put a `tango.yml` file in your repo root so you don't have to pass the command-line options every time:

```yaml
# tango.yml
include_package:
  - preprocess/preprocess_steps.py
  - train/train_steps.py
  - evaluation/eval_steps.py
```

**Comment by BigRedT** [comment]
Awesome, thanks @epwalsh!
