### ISSUE TITLE
MulticoreExecutor incorrectly reports final results

### ISSUE THREAD

**Issue by epwalsh** [allenai/tango#393]
### 🐛 Describe the bug

I'm running two simple steps, one that fails and one that succeeds. When I run this with the `MulticoreExecutor`, it reports that all steps succeeded in the final table, even though one failed.

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/8812459/188994498-8730bc1a-d2b2-4327-b434-4e47f3532537.png">

Here are the steps needed to reproduce:

```python
# steps.py
from tango import Step


@Step.register("hello")
class HelloStep(Step):
    VERSION = "001"
    CACHEABLE = False

    def run(self, name: str) -> str:  # type: ignore
        if name == "Sitka":
            raise ValueError("oh no!")
        return name
```

And the config:

```jsonnet
// config.jsonnet
{
  steps: {
    hello_fail: {
      type: "hello",
      name: "Sitka",
    },
    hello_good: {
      type: "hello",
      name: "Moonshine",
    },
  }
}
```

Then run:

```bash
tango run config.jsonnet i steps.py -j 2
```

### Versions

main branch of tango

**Comment by dirkgr** [comment]
@AkshitaB, can you take a look?

**Comment by AkshitaB** [comment]
@epwalsh I cannot reproduce the error. The logs show failure in the table for me.

<img width="637" alt="Screen Shot 2022-10-12 at 4 34 10 PM" src="https://user-images.githubusercontent.com/6500683/195466685-c190c321-f120-4acc-b6c7-7a6389015dc2.png">

**Comment by epwalsh** [comment]
I'll try to repro again

**Comment by epwalsh** [comment]
Ok I was able to reproduce this again, but only using a local workspace (memory workspace worked fine).

![image](https://user-images.githubusercontent.com/8812459/195668705-318dcb0a-56f3-41bb-9d34-3d1fba988e68.png)
