### ISSUE TITLE
Improve the Tango visualization

### ISSUE THREAD

**Issue by schmmd** [allenai/tango#436]
The current Tango visualization is crude visually and has limited utility when running thousands of steps.  We should determine how to improve the graph visualization when a Tango experiment is simple, and provide an alternate visualization (a tabular view?) when an experiment is highly complex.

Additionally, for many-step experiments that use the Beaker executor, querying Beaker to update the status happens infrequently enough that the view is never up to date.

I believe we might need some changes to the Beaker API to make it easier to update the visualization quickly.  We should figure out what needs to be changed, but organize that work in a separate ticket.

* The visualization doesn't work for runs with 600 steps.
* The server shuts down when the job completes, which is exactly when you want to look at it.
* The API cannot update fully.

**Comment by schmmd** [comment]
![image](https://user-images.githubusercontent.com/954798/193885754-746c9d27-29af-47b7-a42f-66f58e7af117.png)

**Comment by jonborchardt** [comment]
So, you ask, `where are we`?

I have rewritten the tango viz ui in react and it lives here: 
https://github.com/allenai/tangoviz

demo here:
https://tangoviz.apps.allenai.org/

the totally revamps the ui to have a tabular view of all objects in tango and has a new react viz for the node graph.

some neat features:
1- saves recent workspaces in local storage
2- can see all runs in a workspace and sort/filter them
3- can see all referewnced steps of all runs in a workspace and sort/filter them
4- can see details of runs
5- can see details of steps
6- can see a graph of the steps of a run

whats left to do:
1- add support for paginating
2- test on real data
3- have a story for viewing workspaces locally
4- fix up the node graph for huge huge runs

this work is not complete, but we are getting close
