### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by BigRedT** [allenai/tango#449]
What is the best way to pass in command line arguments while running a tango experiment? Specifically, is there a way to modify variables in a jsonnet config file via command line? 

This is useful, for example, when you want to run the same experiment with slightly different parameters in different GNU screen or tmux tabs.

**Comment by epwalsh** [comment]
Hey Tanmay, the easiest way to do that would be to read settings from environment variables (via "extension variables") within your JSONNET config.
For example,

```jsonnet
// config.jsonnet
local pretrained_model = std.extVar("PRETRAINED_MODEL");

...
```

Then you do

```bash
PRETRAINED_MODEL="gpt2" tango run config.jsonnet
```

We had another user ask about this recently, and they proposed adding a command-line option for setting extension variables as an alternative.

**Comment by BigRedT** [comment]
Got it, thanks!
