### ISSUE TITLE
Type mismatch of `train_split` in `FlaxTrainStep`

### ISSUE THREAD

**Issue by reiyw** [allenai/tango#473]
The argument `train_split` of `FlaxTrainStep` is set as `Optional[str]` with the default value of `None`, but the documentation states that the default value is `"train"`:

https://github.com/allenai/tango/blob/ccebb4c71dd5de097668cf652e4e2ddd684d2d25/tango/integrations/flax/train.py#L85

https://github.com/allenai/tango/blob/ccebb4c71dd5de097668cf652e4e2ddd684d2d25/tango/integrations/flax/train.py#L120-L122

Since other `Step`s that also accept `train_split` set it as `train_split: str = "train"`, I thought this should be corrected as follows:

```diff
--- a/tango/integrations/flax/train.py
+++ b/tango/integrations/flax/train.py
@@ -82,7 +82,7 @@ class FlaxTrainStep(Step):
         seed: int = 42,
         keep_checkpoints: int = 5,
         lr_scheduler: Optional[Lazy[LRScheduler]] = None,
-        train_split: Optional[str] = None,
+        train_split: str = "train",
         validation_dataloader: Optional[Lazy[FlaxDataLoader]] = None,
         validation_split: Optional[str] = None,
         train_steps: Optional[int] = None,
```

**Comment by dirkgr** [comment]
I think you are right about this. I made a fix.
